# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ai_pb2 as ai__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiServiceStub(object):
    """Real gRPC entry points for ai-service's own domain logic. ClassifyWaste wraps
    WasteClassifier.classify + save_classification_result + recommend_vendors;
    GetRecommendation wraps waste_recommendations.generate_ai_recommendation.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClassifyWaste = channel.unary_unary(
                '/ai.v1.AiService/ClassifyWaste',
                request_serializer=ai__pb2.ClassifyWasteRequest.SerializeToString,
                response_deserializer=ai__pb2.ClassifyWasteResponse.FromString,
                _registered_method=True)
        self.GetRecommendation = channel.unary_unary(
                '/ai.v1.AiService/GetRecommendation',
                request_serializer=ai__pb2.GetRecommendationRequest.SerializeToString,
                response_deserializer=ai__pb2.GetRecommendationResponse.FromString,
                _registered_method=True)
        self.Chat = channel.unary_unary(
                '/ai.v1.AiService/Chat',
                request_serializer=ai__pb2.ChatRequest.SerializeToString,
                response_deserializer=ai__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.ChatStream = channel.unary_stream(
                '/ai.v1.AiService/ChatStream',
                request_serializer=ai__pb2.ChatRequest.SerializeToString,
                response_deserializer=ai__pb2.ChatChunk.FromString,
                _registered_method=True)
        self.ListChatThreads = channel.unary_unary(
                '/ai.v1.AiService/ListChatThreads',
                request_serializer=ai__pb2.ListChatThreadsRequest.SerializeToString,
                response_deserializer=ai__pb2.ListChatThreadsResponse.FromString,
                _registered_method=True)
        self.GetChatThread = channel.unary_unary(
                '/ai.v1.AiService/GetChatThread',
                request_serializer=ai__pb2.GetChatThreadRequest.SerializeToString,
                response_deserializer=ai__pb2.GetChatThreadResponse.FromString,
                _registered_method=True)
        self.DeleteChatThread = channel.unary_unary(
                '/ai.v1.AiService/DeleteChatThread',
                request_serializer=ai__pb2.DeleteChatThreadRequest.SerializeToString,
                response_deserializer=ai__pb2.DeleteChatThreadResponse.FromString,
                _registered_method=True)


class AiServiceServicer(object):
    """Real gRPC entry points for ai-service's own domain logic. ClassifyWaste wraps
    WasteClassifier.classify + save_classification_result + recommend_vendors;
    GetRecommendation wraps waste_recommendations.generate_ai_recommendation.
    """

    def ClassifyWaste(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecommendation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatStream(self, request, context):
        """Same request as Chat, but streams the reply as it's generated instead of waiting for
        the full turn. `reset` marks a Gemini fallback retry restarting the reply from
        scratch — any text_delta already received for this turn should be discarded and
        display should start over. `done` marks the final chunk (empty text_delta).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChatThreads(self, request, context):
        """Chatbot conversation history, scoped to the caller. ListChatThreads returns the
        caller's past conversations newest-first; GetChatThread returns one thread's full
        message list; DeleteChatThread removes a thread and its messages.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChatThread(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteChatThread(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClassifyWaste': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyWaste,
                    request_deserializer=ai__pb2.ClassifyWasteRequest.FromString,
                    response_serializer=ai__pb2.ClassifyWasteResponse.SerializeToString,
            ),
            'GetRecommendation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecommendation,
                    request_deserializer=ai__pb2.GetRecommendationRequest.FromString,
                    response_serializer=ai__pb2.GetRecommendationResponse.SerializeToString,
            ),
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=ai__pb2.ChatRequest.FromString,
                    response_serializer=ai__pb2.ChatResponse.SerializeToString,
            ),
            'ChatStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatStream,
                    request_deserializer=ai__pb2.ChatRequest.FromString,
                    response_serializer=ai__pb2.ChatChunk.SerializeToString,
            ),
            'ListChatThreads': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChatThreads,
                    request_deserializer=ai__pb2.ListChatThreadsRequest.FromString,
                    response_serializer=ai__pb2.ListChatThreadsResponse.SerializeToString,
            ),
            'GetChatThread': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChatThread,
                    request_deserializer=ai__pb2.GetChatThreadRequest.FromString,
                    response_serializer=ai__pb2.GetChatThreadResponse.SerializeToString,
            ),
            'DeleteChatThread': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteChatThread,
                    request_deserializer=ai__pb2.DeleteChatThreadRequest.FromString,
                    response_serializer=ai__pb2.DeleteChatThreadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.v1.AiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.v1.AiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiService(object):
    """Real gRPC entry points for ai-service's own domain logic. ClassifyWaste wraps
    WasteClassifier.classify + save_classification_result + recommend_vendors;
    GetRecommendation wraps waste_recommendations.generate_ai_recommendation.
    """

    @staticmethod
    def ClassifyWaste(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.v1.AiService/ClassifyWaste',
            ai__pb2.ClassifyWasteRequest.SerializeToString,
            ai__pb2.ClassifyWasteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecommendation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.v1.AiService/GetRecommendation',
            ai__pb2.GetRecommendationRequest.SerializeToString,
            ai__pb2.GetRecommendationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.v1.AiService/Chat',
            ai__pb2.ChatRequest.SerializeToString,
            ai__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai.v1.AiService/ChatStream',
            ai__pb2.ChatRequest.SerializeToString,
            ai__pb2.ChatChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListChatThreads(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.v1.AiService/ListChatThreads',
            ai__pb2.ListChatThreadsRequest.SerializeToString,
            ai__pb2.ListChatThreadsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChatThread(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.v1.AiService/GetChatThread',
            ai__pb2.GetChatThreadRequest.SerializeToString,
            ai__pb2.GetChatThreadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteChatThread(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.v1.AiService/DeleteChatThread',
            ai__pb2.DeleteChatThreadRequest.SerializeToString,
            ai__pb2.DeleteChatThreadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
