// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: ai/v1/ai.proto

package aiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClassifyWasteRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ImageData        []byte                 `protobuf:"bytes,2,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	ImageName        string                 `protobuf:"bytes,3,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	BusinessLocation *string                `protobuf:"bytes,4,opt,name=business_location,json=businessLocation,proto3,oneof" json:"business_location,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClassifyWasteRequest) Reset() {
	*x = ClassifyWasteRequest{}
	mi := &file_ai_v1_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyWasteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyWasteRequest) ProtoMessage() {}

func (x *ClassifyWasteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyWasteRequest.ProtoReflect.Descriptor instead.
func (*ClassifyWasteRequest) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{0}
}

func (x *ClassifyWasteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ClassifyWasteRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *ClassifyWasteRequest) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *ClassifyWasteRequest) GetBusinessLocation() string {
	if x != nil && x.BusinessLocation != nil {
		return *x.BusinessLocation
	}
	return ""
}

type DetectedItem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Description      string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Category         string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Confidence       float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	MaterialEvidence string                 `protobuf:"bytes,4,opt,name=material_evidence,json=materialEvidence,proto3" json:"material_evidence,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DetectedItem) Reset() {
	*x = DetectedItem{}
	mi := &file_ai_v1_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectedItem) ProtoMessage() {}

func (x *DetectedItem) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectedItem.ProtoReflect.Descriptor instead.
func (*DetectedItem) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{1}
}

func (x *DetectedItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DetectedItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *DetectedItem) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *DetectedItem) GetMaterialEvidence() string {
	if x != nil {
		return x.MaterialEvidence
	}
	return ""
}

type Vendor struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OfferPrice      *float64               `protobuf:"fixed64,2,opt,name=offer_price,json=offerPrice,proto3,oneof" json:"offer_price,omitempty"`
	Location        *string                `protobuf:"bytes,3,opt,name=location,proto3,oneof" json:"location,omitempty"`
	PickupAvailable *bool                  `protobuf:"varint,4,opt,name=pickup_available,json=pickupAvailable,proto3,oneof" json:"pickup_available,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Vendor) Reset() {
	*x = Vendor{}
	mi := &file_ai_v1_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vendor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vendor) ProtoMessage() {}

func (x *Vendor) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vendor.ProtoReflect.Descriptor instead.
func (*Vendor) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{2}
}

func (x *Vendor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Vendor) GetOfferPrice() float64 {
	if x != nil && x.OfferPrice != nil {
		return *x.OfferPrice
	}
	return 0
}

func (x *Vendor) GetLocation() string {
	if x != nil && x.Location != nil {
		return *x.Location
	}
	return ""
}

func (x *Vendor) GetPickupAvailable() bool {
	if x != nil && x.PickupAvailable != nil {
		return *x.PickupAvailable
	}
	return false
}

type VendorList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vendors       []*Vendor              `protobuf:"bytes,1,rep,name=vendors,proto3" json:"vendors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VendorList) Reset() {
	*x = VendorList{}
	mi := &file_ai_v1_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VendorList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendorList) ProtoMessage() {}

func (x *VendorList) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendorList.ProtoReflect.Descriptor instead.
func (*VendorList) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{3}
}

func (x *VendorList) GetVendors() []*Vendor {
	if x != nil {
		return x.Vendors
	}
	return nil
}

type ClassifyWasteResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ClassificationId   string                 `protobuf:"bytes,1,opt,name=classification_id,json=classificationId,proto3" json:"classification_id,omitempty"`
	PrimaryCategory    string                 `protobuf:"bytes,2,opt,name=primary_category,json=primaryCategory,proto3" json:"primary_category,omitempty"`
	Confidence         float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Items              []*DetectedItem        `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	IsMixed            bool                   `protobuf:"varint,5,opt,name=is_mixed,json=isMixed,proto3" json:"is_mixed,omitempty"`
	HazardFlag         bool                   `protobuf:"varint,6,opt,name=hazard_flag,json=hazardFlag,proto3" json:"hazard_flag,omitempty"`
	HazardReason       string                 `protobuf:"bytes,7,opt,name=hazard_reason,json=hazardReason,proto3" json:"hazard_reason,omitempty"`
	ContaminationNotes string                 `protobuf:"bytes,8,opt,name=contamination_notes,json=contaminationNotes,proto3" json:"contamination_notes,omitempty"`
	Reasoning          string                 `protobuf:"bytes,9,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	NeedsReview        bool                   `protobuf:"varint,10,opt,name=needs_review,json=needsReview,proto3" json:"needs_review,omitempty"`
	VendorsByCategory  map[string]*VendorList `protobuf:"bytes,11,rep,name=vendors_by_category,json=vendorsByCategory,proto3" json:"vendors_by_category,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ClassifyWasteResponse) Reset() {
	*x = ClassifyWasteResponse{}
	mi := &file_ai_v1_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyWasteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyWasteResponse) ProtoMessage() {}

func (x *ClassifyWasteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyWasteResponse.ProtoReflect.Descriptor instead.
func (*ClassifyWasteResponse) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{4}
}

func (x *ClassifyWasteResponse) GetClassificationId() string {
	if x != nil {
		return x.ClassificationId
	}
	return ""
}

func (x *ClassifyWasteResponse) GetPrimaryCategory() string {
	if x != nil {
		return x.PrimaryCategory
	}
	return ""
}

func (x *ClassifyWasteResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ClassifyWasteResponse) GetItems() []*DetectedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ClassifyWasteResponse) GetIsMixed() bool {
	if x != nil {
		return x.IsMixed
	}
	return false
}

func (x *ClassifyWasteResponse) GetHazardFlag() bool {
	if x != nil {
		return x.HazardFlag
	}
	return false
}

func (x *ClassifyWasteResponse) GetHazardReason() string {
	if x != nil {
		return x.HazardReason
	}
	return ""
}

func (x *ClassifyWasteResponse) GetContaminationNotes() string {
	if x != nil {
		return x.ContaminationNotes
	}
	return ""
}

func (x *ClassifyWasteResponse) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *ClassifyWasteResponse) GetNeedsReview() bool {
	if x != nil {
		return x.NeedsReview
	}
	return false
}

func (x *ClassifyWasteResponse) GetVendorsByCategory() map[string]*VendorList {
	if x != nil {
		return x.VendorsByCategory
	}
	return nil
}

type GetRecommendationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ScanLimit     int32                  `protobuf:"varint,2,opt,name=scan_limit,json=scanLimit,proto3" json:"scan_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendationRequest) Reset() {
	*x = GetRecommendationRequest{}
	mi := &file_ai_v1_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationRequest) ProtoMessage() {}

func (x *GetRecommendationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationRequest.ProtoReflect.Descriptor instead.
func (*GetRecommendationRequest) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{5}
}

func (x *GetRecommendationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRecommendationRequest) GetScanLimit() int32 {
	if x != nil {
		return x.ScanLimit
	}
	return 0
}

type GetRecommendationResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RecommendationText string                 `protobuf:"bytes,1,opt,name=recommendation_text,json=recommendationText,proto3" json:"recommendation_text,omitempty"`
	GeneratedAt        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetRecommendationResponse) Reset() {
	*x = GetRecommendationResponse{}
	mi := &file_ai_v1_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationResponse) ProtoMessage() {}

func (x *GetRecommendationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationResponse.ProtoReflect.Descriptor instead.
func (*GetRecommendationResponse) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{6}
}

func (x *GetRecommendationResponse) GetRecommendationText() string {
	if x != nil {
		return x.RecommendationText
	}
	return ""
}

func (x *GetRecommendationResponse) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

type ChatRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	UserId   string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message  string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ThreadId *string                `protobuf:"bytes,3,opt,name=thread_id,json=threadId,proto3,oneof" json:"thread_id,omitempty"`
	// Optional attachment for the turn. media_data is the raw file bytes; media_type is its
	// MIME type (e.g. image/jpeg, video/mp4, application/pdf); media_name is the original
	// filename. Images/video/pdf/audio are forwarded to the multimodal model; other types are
	// referenced by name only. Not replayed on later turns — only the current turn sees it.
	MediaData     []byte `protobuf:"bytes,4,opt,name=media_data,json=mediaData,proto3" json:"media_data,omitempty"`
	MediaType     string `protobuf:"bytes,5,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	MediaName     string `protobuf:"bytes,6,opt,name=media_name,json=mediaName,proto3" json:"media_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_ai_v1_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{7}
}

func (x *ChatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetThreadId() string {
	if x != nil && x.ThreadId != nil {
		return *x.ThreadId
	}
	return ""
}

func (x *ChatRequest) GetMediaData() []byte {
	if x != nil {
		return x.MediaData
	}
	return nil
}

func (x *ChatRequest) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *ChatRequest) GetMediaName() string {
	if x != nil {
		return x.MediaName
	}
	return ""
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	ThreadId      string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_ai_v1_ai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{8}
}

func (x *ChatResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *ChatResponse) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

type ChatChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TextDelta     string                 `protobuf:"bytes,1,opt,name=text_delta,json=textDelta,proto3" json:"text_delta,omitempty"`
	ThreadId      string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Done          bool                   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	Reset_        bool                   `protobuf:"varint,4,opt,name=reset,proto3" json:"reset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatChunk) Reset() {
	*x = ChatChunk{}
	mi := &file_ai_v1_ai_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatChunk) ProtoMessage() {}

func (x *ChatChunk) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatChunk.ProtoReflect.Descriptor instead.
func (*ChatChunk) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{9}
}

func (x *ChatChunk) GetTextDelta() string {
	if x != nil {
		return x.TextDelta
	}
	return ""
}

func (x *ChatChunk) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *ChatChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ChatChunk) GetReset_() bool {
	if x != nil {
		return x.Reset_
	}
	return false
}

type ChatThreadSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"` // derived from the first user message; may be empty for an empty thread
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatThreadSummary) Reset() {
	*x = ChatThreadSummary{}
	mi := &file_ai_v1_ai_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatThreadSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatThreadSummary) ProtoMessage() {}

func (x *ChatThreadSummary) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatThreadSummary.ProtoReflect.Descriptor instead.
func (*ChatThreadSummary) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{10}
}

func (x *ChatThreadSummary) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *ChatThreadSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ChatThreadSummary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ChatThreadSummary) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ChatHistoryMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // "human" or "ai"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	MediaName     string                 `protobuf:"bytes,3,opt,name=media_name,json=mediaName,proto3" json:"media_name,omitempty"`
	MediaType     string                 `protobuf:"bytes,4,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatHistoryMessage) Reset() {
	*x = ChatHistoryMessage{}
	mi := &file_ai_v1_ai_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatHistoryMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatHistoryMessage) ProtoMessage() {}

func (x *ChatHistoryMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatHistoryMessage.ProtoReflect.Descriptor instead.
func (*ChatHistoryMessage) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{11}
}

func (x *ChatHistoryMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatHistoryMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatHistoryMessage) GetMediaName() string {
	if x != nil {
		return x.MediaName
	}
	return ""
}

func (x *ChatHistoryMessage) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *ChatHistoryMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListChatThreadsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatThreadsRequest) Reset() {
	*x = ListChatThreadsRequest{}
	mi := &file_ai_v1_ai_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatThreadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatThreadsRequest) ProtoMessage() {}

func (x *ListChatThreadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatThreadsRequest.ProtoReflect.Descriptor instead.
func (*ListChatThreadsRequest) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{12}
}

func (x *ListChatThreadsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListChatThreadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Threads       []*ChatThreadSummary   `protobuf:"bytes,1,rep,name=threads,proto3" json:"threads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatThreadsResponse) Reset() {
	*x = ListChatThreadsResponse{}
	mi := &file_ai_v1_ai_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatThreadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatThreadsResponse) ProtoMessage() {}

func (x *ListChatThreadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatThreadsResponse.ProtoReflect.Descriptor instead.
func (*ListChatThreadsResponse) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{13}
}

func (x *ListChatThreadsResponse) GetThreads() []*ChatThreadSummary {
	if x != nil {
		return x.Threads
	}
	return nil
}

type GetChatThreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ThreadId      string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatThreadRequest) Reset() {
	*x = GetChatThreadRequest{}
	mi := &file_ai_v1_ai_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatThreadRequest) ProtoMessage() {}

func (x *GetChatThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatThreadRequest.ProtoReflect.Descriptor instead.
func (*GetChatThreadRequest) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{14}
}

func (x *GetChatThreadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetChatThreadRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

type GetChatThreadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Messages      []*ChatHistoryMessage  `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatThreadResponse) Reset() {
	*x = GetChatThreadResponse{}
	mi := &file_ai_v1_ai_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatThreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatThreadResponse) ProtoMessage() {}

func (x *GetChatThreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatThreadResponse.ProtoReflect.Descriptor instead.
func (*GetChatThreadResponse) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{15}
}

func (x *GetChatThreadResponse) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *GetChatThreadResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetChatThreadResponse) GetMessages() []*ChatHistoryMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type DeleteChatThreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ThreadId      string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatThreadRequest) Reset() {
	*x = DeleteChatThreadRequest{}
	mi := &file_ai_v1_ai_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatThreadRequest) ProtoMessage() {}

func (x *DeleteChatThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatThreadRequest.ProtoReflect.Descriptor instead.
func (*DeleteChatThreadRequest) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteChatThreadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteChatThreadRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

type DeleteChatThreadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatThreadResponse) Reset() {
	*x = DeleteChatThreadResponse{}
	mi := &file_ai_v1_ai_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatThreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatThreadResponse) ProtoMessage() {}

func (x *DeleteChatThreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatThreadResponse.ProtoReflect.Descriptor instead.
func (*DeleteChatThreadResponse) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{17}
}

var File_ai_v1_ai_proto protoreflect.FileDescriptor

const file_ai_v1_ai_proto_rawDesc = "" +
	"\n" +
	"\x0eai/v1/ai.proto\x12\x05ai.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb5\x01\n" +
	"\x14ClassifyWasteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"image_data\x18\x02 \x01(\fR\timageData\x12\x1d\n" +
	"\n" +
	"image_name\x18\x03 \x01(\tR\timageName\x120\n" +
	"\x11business_location\x18\x04 \x01(\tH\x00R\x10businessLocation\x88\x01\x01B\x14\n" +
	"\x12_business_location\"\x99\x01\n" +
	"\fDetectedItem\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12+\n" +
	"\x11material_evidence\x18\x04 \x01(\tR\x10materialEvidence\"\xc5\x01\n" +
	"\x06Vendor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12$\n" +
	"\voffer_price\x18\x02 \x01(\x01H\x00R\n" +
	"offerPrice\x88\x01\x01\x12\x1f\n" +
	"\blocation\x18\x03 \x01(\tH\x01R\blocation\x88\x01\x01\x12.\n" +
	"\x10pickup_available\x18\x04 \x01(\bH\x02R\x0fpickupAvailable\x88\x01\x01B\x0e\n" +
	"\f_offer_priceB\v\n" +
	"\t_locationB\x13\n" +
	"\x11_pickup_available\"5\n" +
	"\n" +
	"VendorList\x12'\n" +
	"\avendors\x18\x01 \x03(\v2\r.ai.v1.VendorR\avendors\"\xcb\x04\n" +
	"\x15ClassifyWasteResponse\x12+\n" +
	"\x11classification_id\x18\x01 \x01(\tR\x10classificationId\x12)\n" +
	"\x10primary_category\x18\x02 \x01(\tR\x0fprimaryCategory\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12)\n" +
	"\x05items\x18\x04 \x03(\v2\x13.ai.v1.DetectedItemR\x05items\x12\x19\n" +
	"\bis_mixed\x18\x05 \x01(\bR\aisMixed\x12\x1f\n" +
	"\vhazard_flag\x18\x06 \x01(\bR\n" +
	"hazardFlag\x12#\n" +
	"\rhazard_reason\x18\a \x01(\tR\fhazardReason\x12/\n" +
	"\x13contamination_notes\x18\b \x01(\tR\x12contaminationNotes\x12\x1c\n" +
	"\treasoning\x18\t \x01(\tR\treasoning\x12!\n" +
	"\fneeds_review\x18\n" +
	" \x01(\bR\vneedsReview\x12c\n" +
	"\x13vendors_by_category\x18\v \x03(\v23.ai.v1.ClassifyWasteResponse.VendorsByCategoryEntryR\x11vendorsByCategory\x1aW\n" +
	"\x16VendorsByCategoryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.ai.v1.VendorListR\x05value:\x028\x01\"R\n" +
	"\x18GetRecommendationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"scan_limit\x18\x02 \x01(\x05R\tscanLimit\"\x8b\x01\n" +
	"\x19GetRecommendationResponse\x12/\n" +
	"\x13recommendation_text\x18\x01 \x01(\tR\x12recommendationText\x12=\n" +
	"\fgenerated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\"\xcd\x01\n" +
	"\vChatRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12 \n" +
	"\tthread_id\x18\x03 \x01(\tH\x00R\bthreadId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"media_data\x18\x04 \x01(\fR\tmediaData\x12\x1d\n" +
	"\n" +
	"media_type\x18\x05 \x01(\tR\tmediaType\x12\x1d\n" +
	"\n" +
	"media_name\x18\x06 \x01(\tR\tmediaNameB\f\n" +
	"\n" +
	"_thread_id\"A\n" +
	"\fChatResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\"q\n" +
	"\tChatChunk\x12\x1d\n" +
	"\n" +
	"text_delta\x18\x01 \x01(\tR\ttextDelta\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done\x12\x14\n" +
	"\x05reset\x18\x04 \x01(\bR\x05reset\"\xbc\x01\n" +
	"\x11ChatThreadSummary\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xbb\x01\n" +
	"\x12ChatHistoryMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"media_name\x18\x03 \x01(\tR\tmediaName\x12\x1d\n" +
	"\n" +
	"media_type\x18\x04 \x01(\tR\tmediaType\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"1\n" +
	"\x16ListChatThreadsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"M\n" +
	"\x17ListChatThreadsResponse\x122\n" +
	"\athreads\x18\x01 \x03(\v2\x18.ai.v1.ChatThreadSummaryR\athreads\"L\n" +
	"\x14GetChatThreadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\"\x81\x01\n" +
	"\x15GetChatThreadResponse\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x125\n" +
	"\bmessages\x18\x03 \x03(\v2\x19.ai.v1.ChatHistoryMessageR\bmessages\"O\n" +
	"\x17DeleteChatThreadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\"\x1a\n" +
	"\x18DeleteChatThreadResponse2\x89\x04\n" +
	"\tAiService\x12J\n" +
	"\rClassifyWaste\x12\x1b.ai.v1.ClassifyWasteRequest\x1a\x1c.ai.v1.ClassifyWasteResponse\x12V\n" +
	"\x11GetRecommendation\x12\x1f.ai.v1.GetRecommendationRequest\x1a .ai.v1.GetRecommendationResponse\x12/\n" +
	"\x04Chat\x12\x12.ai.v1.ChatRequest\x1a\x13.ai.v1.ChatResponse\x124\n" +
	"\n" +
	"ChatStream\x12\x12.ai.v1.ChatRequest\x1a\x10.ai.v1.ChatChunk0\x01\x12P\n" +
	"\x0fListChatThreads\x12\x1d.ai.v1.ListChatThreadsRequest\x1a\x1e.ai.v1.ListChatThreadsResponse\x12J\n" +
	"\rGetChatThread\x12\x1b.ai.v1.GetChatThreadRequest\x1a\x1c.ai.v1.GetChatThreadResponse\x12S\n" +
	"\x10DeleteChatThread\x12\x1e.ai.v1.DeleteChatThreadRequest\x1a\x1f.ai.v1.DeleteChatThreadResponseB2Z0notification-service/internal/grpcgen/ai/v1;aiv1b\x06proto3"

var (
	file_ai_v1_ai_proto_rawDescOnce sync.Once
	file_ai_v1_ai_proto_rawDescData []byte
)

func file_ai_v1_ai_proto_rawDescGZIP() []byte {
	file_ai_v1_ai_proto_rawDescOnce.Do(func() {
		file_ai_v1_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_v1_ai_proto_rawDesc), len(file_ai_v1_ai_proto_rawDesc)))
	})
	return file_ai_v1_ai_proto_rawDescData
}

var file_ai_v1_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_ai_v1_ai_proto_goTypes = []any{
	(*ClassifyWasteRequest)(nil),      // 0: ai.v1.ClassifyWasteRequest
	(*DetectedItem)(nil),              // 1: ai.v1.DetectedItem
	(*Vendor)(nil),                    // 2: ai.v1.Vendor
	(*VendorList)(nil),                // 3: ai.v1.VendorList
	(*ClassifyWasteResponse)(nil),     // 4: ai.v1.ClassifyWasteResponse
	(*GetRecommendationRequest)(nil),  // 5: ai.v1.GetRecommendationRequest
	(*GetRecommendationResponse)(nil), // 6: ai.v1.GetRecommendationResponse
	(*ChatRequest)(nil),               // 7: ai.v1.ChatRequest
	(*ChatResponse)(nil),              // 8: ai.v1.ChatResponse
	(*ChatChunk)(nil),                 // 9: ai.v1.ChatChunk
	(*ChatThreadSummary)(nil),         // 10: ai.v1.ChatThreadSummary
	(*ChatHistoryMessage)(nil),        // 11: ai.v1.ChatHistoryMessage
	(*ListChatThreadsRequest)(nil),    // 12: ai.v1.ListChatThreadsRequest
	(*ListChatThreadsResponse)(nil),   // 13: ai.v1.ListChatThreadsResponse
	(*GetChatThreadRequest)(nil),      // 14: ai.v1.GetChatThreadRequest
	(*GetChatThreadResponse)(nil),     // 15: ai.v1.GetChatThreadResponse
	(*DeleteChatThreadRequest)(nil),   // 16: ai.v1.DeleteChatThreadRequest
	(*DeleteChatThreadResponse)(nil),  // 17: ai.v1.DeleteChatThreadResponse
	nil,                               // 18: ai.v1.ClassifyWasteResponse.VendorsByCategoryEntry
	(*timestamppb.Timestamp)(nil),     // 19: google.protobuf.Timestamp
}
var file_ai_v1_ai_proto_depIdxs = []int32{
	2,  // 0: ai.v1.VendorList.vendors:type_name -> ai.v1.Vendor
	1,  // 1: ai.v1.ClassifyWasteResponse.items:type_name -> ai.v1.DetectedItem
	18, // 2: ai.v1.ClassifyWasteResponse.vendors_by_category:type_name -> ai.v1.ClassifyWasteResponse.VendorsByCategoryEntry
	19, // 3: ai.v1.GetRecommendationResponse.generated_at:type_name -> google.protobuf.Timestamp
	19, // 4: ai.v1.ChatThreadSummary.created_at:type_name -> google.protobuf.Timestamp
	19, // 5: ai.v1.ChatThreadSummary.updated_at:type_name -> google.protobuf.Timestamp
	19, // 6: ai.v1.ChatHistoryMessage.created_at:type_name -> google.protobuf.Timestamp
	10, // 7: ai.v1.ListChatThreadsResponse.threads:type_name -> ai.v1.ChatThreadSummary
	11, // 8: ai.v1.GetChatThreadResponse.messages:type_name -> ai.v1.ChatHistoryMessage
	3,  // 9: ai.v1.ClassifyWasteResponse.VendorsByCategoryEntry.value:type_name -> ai.v1.VendorList
	0,  // 10: ai.v1.AiService.ClassifyWaste:input_type -> ai.v1.ClassifyWasteRequest
	5,  // 11: ai.v1.AiService.GetRecommendation:input_type -> ai.v1.GetRecommendationRequest
	7,  // 12: ai.v1.AiService.Chat:input_type -> ai.v1.ChatRequest
	7,  // 13: ai.v1.AiService.ChatStream:input_type -> ai.v1.ChatRequest
	12, // 14: ai.v1.AiService.ListChatThreads:input_type -> ai.v1.ListChatThreadsRequest
	14, // 15: ai.v1.AiService.GetChatThread:input_type -> ai.v1.GetChatThreadRequest
	16, // 16: ai.v1.AiService.DeleteChatThread:input_type -> ai.v1.DeleteChatThreadRequest
	4,  // 17: ai.v1.AiService.ClassifyWaste:output_type -> ai.v1.ClassifyWasteResponse
	6,  // 18: ai.v1.AiService.GetRecommendation:output_type -> ai.v1.GetRecommendationResponse
	8,  // 19: ai.v1.AiService.Chat:output_type -> ai.v1.ChatResponse
	9,  // 20: ai.v1.AiService.ChatStream:output_type -> ai.v1.ChatChunk
	13, // 21: ai.v1.AiService.ListChatThreads:output_type -> ai.v1.ListChatThreadsResponse
	15, // 22: ai.v1.AiService.GetChatThread:output_type -> ai.v1.GetChatThreadResponse
	17, // 23: ai.v1.AiService.DeleteChatThread:output_type -> ai.v1.DeleteChatThreadResponse
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_ai_v1_ai_proto_init() }
func file_ai_v1_ai_proto_init() {
	if File_ai_v1_ai_proto != nil {
		return
	}
	file_ai_v1_ai_proto_msgTypes[0].OneofWrappers = []any{}
	file_ai_v1_ai_proto_msgTypes[2].OneofWrappers = []any{}
	file_ai_v1_ai_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_v1_ai_proto_rawDesc), len(file_ai_v1_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_v1_ai_proto_goTypes,
		DependencyIndexes: file_ai_v1_ai_proto_depIdxs,
		MessageInfos:      file_ai_v1_ai_proto_msgTypes,
	}.Build()
	File_ai_v1_ai_proto = out.File
	file_ai_v1_ai_proto_goTypes = nil
	file_ai_v1_ai_proto_depIdxs = nil
}
