// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: ai/v1/ai.proto

package aiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AiService_ClassifyWaste_FullMethodName     = "/ai.v1.AiService/ClassifyWaste"
	AiService_GetRecommendation_FullMethodName = "/ai.v1.AiService/GetRecommendation"
	AiService_Chat_FullMethodName              = "/ai.v1.AiService/Chat"
	AiService_ChatStream_FullMethodName        = "/ai.v1.AiService/ChatStream"
	AiService_ListChatThreads_FullMethodName   = "/ai.v1.AiService/ListChatThreads"
	AiService_GetChatThread_FullMethodName     = "/ai.v1.AiService/GetChatThread"
	AiService_DeleteChatThread_FullMethodName  = "/ai.v1.AiService/DeleteChatThread"
)

// AiServiceClient is the client API for AiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Real gRPC entry points for ai-service's own domain logic. ClassifyWaste wraps
// WasteClassifier.classify + save_classification_result + recommend_vendors;
// GetRecommendation wraps waste_recommendations.generate_ai_recommendation.
type AiServiceClient interface {
	ClassifyWaste(ctx context.Context, in *ClassifyWasteRequest, opts ...grpc.CallOption) (*ClassifyWasteResponse, error)
	GetRecommendation(ctx context.Context, in *GetRecommendationRequest, opts ...grpc.CallOption) (*GetRecommendationResponse, error)
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
	// Same request as Chat, but streams the reply as it's generated instead of waiting for
	// the full turn. `reset` marks a Gemini fallback retry restarting the reply from
	// scratch — any text_delta already received for this turn should be discarded and
	// display should start over. `done` marks the final chunk (empty text_delta).
	ChatStream(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatChunk], error)
	// Chatbot conversation history, scoped to the caller. ListChatThreads returns the
	// caller's past conversations newest-first; GetChatThread returns one thread's full
	// message list; DeleteChatThread removes a thread and its messages.
	ListChatThreads(ctx context.Context, in *ListChatThreadsRequest, opts ...grpc.CallOption) (*ListChatThreadsResponse, error)
	GetChatThread(ctx context.Context, in *GetChatThreadRequest, opts ...grpc.CallOption) (*GetChatThreadResponse, error)
	DeleteChatThread(ctx context.Context, in *DeleteChatThreadRequest, opts ...grpc.CallOption) (*DeleteChatThreadResponse, error)
}

type aiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAiServiceClient(cc grpc.ClientConnInterface) AiServiceClient {
	return &aiServiceClient{cc}
}

func (c *aiServiceClient) ClassifyWaste(ctx context.Context, in *ClassifyWasteRequest, opts ...grpc.CallOption) (*ClassifyWasteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassifyWasteResponse)
	err := c.cc.Invoke(ctx, AiService_ClassifyWaste_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiServiceClient) GetRecommendation(ctx context.Context, in *GetRecommendationRequest, opts ...grpc.CallOption) (*GetRecommendationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecommendationResponse)
	err := c.cc.Invoke(ctx, AiService_GetRecommendation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, AiService_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiServiceClient) ChatStream(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AiService_ServiceDesc.Streams[0], AiService_ChatStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AiService_ChatStreamClient = grpc.ServerStreamingClient[ChatChunk]

func (c *aiServiceClient) ListChatThreads(ctx context.Context, in *ListChatThreadsRequest, opts ...grpc.CallOption) (*ListChatThreadsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChatThreadsResponse)
	err := c.cc.Invoke(ctx, AiService_ListChatThreads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiServiceClient) GetChatThread(ctx context.Context, in *GetChatThreadRequest, opts ...grpc.CallOption) (*GetChatThreadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChatThreadResponse)
	err := c.cc.Invoke(ctx, AiService_GetChatThread_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiServiceClient) DeleteChatThread(ctx context.Context, in *DeleteChatThreadRequest, opts ...grpc.CallOption) (*DeleteChatThreadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteChatThreadResponse)
	err := c.cc.Invoke(ctx, AiService_DeleteChatThread_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiServiceServer is the server API for AiService service.
// All implementations should embed UnimplementedAiServiceServer
// for forward compatibility.
//
// Real gRPC entry points for ai-service's own domain logic. ClassifyWaste wraps
// WasteClassifier.classify + save_classification_result + recommend_vendors;
// GetRecommendation wraps waste_recommendations.generate_ai_recommendation.
type AiServiceServer interface {
	ClassifyWaste(context.Context, *ClassifyWasteRequest) (*ClassifyWasteResponse, error)
	GetRecommendation(context.Context, *GetRecommendationRequest) (*GetRecommendationResponse, error)
	Chat(context.Context, *ChatRequest) (*ChatResponse, error)
	// Same request as Chat, but streams the reply as it's generated instead of waiting for
	// the full turn. `reset` marks a Gemini fallback retry restarting the reply from
	// scratch — any text_delta already received for this turn should be discarded and
	// display should start over. `done` marks the final chunk (empty text_delta).
	ChatStream(*ChatRequest, grpc.ServerStreamingServer[ChatChunk]) error
	// Chatbot conversation history, scoped to the caller. ListChatThreads returns the
	// caller's past conversations newest-first; GetChatThread returns one thread's full
	// message list; DeleteChatThread removes a thread and its messages.
	ListChatThreads(context.Context, *ListChatThreadsRequest) (*ListChatThreadsResponse, error)
	GetChatThread(context.Context, *GetChatThreadRequest) (*GetChatThreadResponse, error)
	DeleteChatThread(context.Context, *DeleteChatThreadRequest) (*DeleteChatThreadResponse, error)
}

// UnimplementedAiServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiServiceServer struct{}

func (UnimplementedAiServiceServer) ClassifyWaste(context.Context, *ClassifyWasteRequest) (*ClassifyWasteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClassifyWaste not implemented")
}
func (UnimplementedAiServiceServer) GetRecommendation(context.Context, *GetRecommendationRequest) (*GetRecommendationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecommendation not implemented")
}
func (UnimplementedAiServiceServer) Chat(context.Context, *ChatRequest) (*ChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedAiServiceServer) ChatStream(*ChatRequest, grpc.ServerStreamingServer[ChatChunk]) error {
	return status.Error(codes.Unimplemented, "method ChatStream not implemented")
}
func (UnimplementedAiServiceServer) ListChatThreads(context.Context, *ListChatThreadsRequest) (*ListChatThreadsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListChatThreads not implemented")
}
func (UnimplementedAiServiceServer) GetChatThread(context.Context, *GetChatThreadRequest) (*GetChatThreadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChatThread not implemented")
}
func (UnimplementedAiServiceServer) DeleteChatThread(context.Context, *DeleteChatThreadRequest) (*DeleteChatThreadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteChatThread not implemented")
}
func (UnimplementedAiServiceServer) testEmbeddedByValue() {}

// UnsafeAiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiServiceServer will
// result in compilation errors.
type UnsafeAiServiceServer interface {
	mustEmbedUnimplementedAiServiceServer()
}

func RegisterAiServiceServer(s grpc.ServiceRegistrar, srv AiServiceServer) {
	// If the following call panics, it indicates UnimplementedAiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AiService_ServiceDesc, srv)
}

func _AiService_ClassifyWaste_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifyWasteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServiceServer).ClassifyWaste(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiService_ClassifyWaste_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServiceServer).ClassifyWaste(ctx, req.(*ClassifyWasteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiService_GetRecommendation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecommendationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServiceServer).GetRecommendation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiService_GetRecommendation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServiceServer).GetRecommendation(ctx, req.(*GetRecommendationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiService_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServiceServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiService_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServiceServer).Chat(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiService_ChatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AiServiceServer).ChatStream(m, &grpc.GenericServerStream[ChatRequest, ChatChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AiService_ChatStreamServer = grpc.ServerStreamingServer[ChatChunk]

func _AiService_ListChatThreads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChatThreadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServiceServer).ListChatThreads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiService_ListChatThreads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServiceServer).ListChatThreads(ctx, req.(*ListChatThreadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiService_GetChatThread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatThreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServiceServer).GetChatThread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiService_GetChatThread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServiceServer).GetChatThread(ctx, req.(*GetChatThreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiService_DeleteChatThread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChatThreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServiceServer).DeleteChatThread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiService_DeleteChatThread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServiceServer).DeleteChatThread(ctx, req.(*DeleteChatThreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AiService_ServiceDesc is the grpc.ServiceDesc for AiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.v1.AiService",
	HandlerType: (*AiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClassifyWaste",
			Handler:    _AiService_ClassifyWaste_Handler,
		},
		{
			MethodName: "GetRecommendation",
			Handler:    _AiService_GetRecommendation_Handler,
		},
		{
			MethodName: "Chat",
			Handler:    _AiService_Chat_Handler,
		},
		{
			MethodName: "ListChatThreads",
			Handler:    _AiService_ListChatThreads_Handler,
		},
		{
			MethodName: "GetChatThread",
			Handler:    _AiService_GetChatThread_Handler,
		},
		{
			MethodName: "DeleteChatThread",
			Handler:    _AiService_DeleteChatThread_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatStream",
			Handler:       _AiService_ChatStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ai/v1/ai.proto",
}
